/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.time.Clock;
import javax.swing.JOptionPane;

/**
 *
 * @author jeferson.agudelo
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        //    txtContador.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNumero1 = new javax.swing.JTextField();
        txtNumero2 = new javax.swing.JTextField();
        txtNumero3 = new javax.swing.JTextField();
        txtNumero4 = new javax.swing.JTextField();
        txtNumero5 = new javax.swing.JTextField();
        txtNumero6 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtContador = new javax.swing.JTextField();
        txtContador2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cbxOrdenamiento = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNumero1.setFont(new java.awt.Font("Segoe UI Semibold", 2, 36)); // NOI18N
        txtNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumero1ActionPerformed(evt);
            }
        });

        txtNumero2.setFont(new java.awt.Font("Segoe UI Semibold", 2, 36)); // NOI18N

        txtNumero3.setFont(new java.awt.Font("Segoe UI Semibold", 2, 36)); // NOI18N

        txtNumero4.setFont(new java.awt.Font("Segoe UI Semibold", 2, 36)); // NOI18N

        txtNumero5.setFont(new java.awt.Font("Segoe UI Semibold", 2, 36)); // NOI18N
        txtNumero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumero5ActionPerformed(evt);
            }
        });

        txtNumero6.setFont(new java.awt.Font("Segoe UI Semibold", 2, 36)); // NOI18N

        jLabel3.setText("INGRESE LOS VALORES DEL VECTOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(txtNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(txtNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(txtNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txtNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(txtNumero6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero6)
                    .addComponent(txtNumero5)
                    .addComponent(txtNumero4)
                    .addComponent(txtNumero3)
                    .addComponent(txtNumero1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtContador.setEditable(false);
        txtContador.setText("0");
        txtContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContadorActionPerformed(evt);
            }
        });

        txtContador2.setEditable(false);
        txtContador2.setText("5");
        txtContador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContador2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtContador2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContador, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtContador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContador2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setText("ORDENAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbxOrdenamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Burbuja", "Seleccion", "Insercion" }));

        jLabel1.setText("ESCOJA EL METODO DE ORDENAMEINTO");

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel2.setText("ORDENAMIENTO");

        jButton2.setText("NUEVO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(cbxOrdenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(100, 100, 100)
                        .addComponent(jButton2)
                        .addGap(84, 84, 84)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxOrdenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String num1 = txtNumero1.getText();
        String num2 = txtNumero2.getText();
        String num3 = txtNumero3.getText();
        String num4 = txtNumero4.getText();
        String num5 = txtNumero5.getText();
        String num6 = txtNumero6.getText();

        if ("".equals(num1)) {
            JOptionPane.showMessageDialog(null, "por favor ingresar valor en el campo 1");
        } else {
            if ("".equals(num2)) {
                JOptionPane.showMessageDialog(null, "por favor ingresar valor en el campo 2");
            } else {
                if ("".equals(num3)) {
                    JOptionPane.showMessageDialog(null, "por favor ingresar valor en el campo 3");
                } else {
                    if ("".equals(num4)) {
                        JOptionPane.showMessageDialog(null, "por favor ingresar valor en el campo 4");
                    } else {
                        if ("".equals(num5)) {
                            JOptionPane.showMessageDialog(null, "por favor ingresar valor en el campo 5");
                        } else {
                            if ("".equals(num6)) {
                                JOptionPane.showMessageDialog(null, "por favor ingresar valor en el campo 6");
                            } else {

                                try {

                                    cbxOrdenamiento.setEnabled(false);
                                    txtNumero1.setEnabled(false);
                                    txtNumero2.setEnabled(false);
                                    txtNumero3.setEnabled(false);
                                    txtNumero4.setEnabled(false);
                                    txtNumero5.setEnabled(false);
                                    txtNumero6.setEnabled(false);

                                    int[] arreglo = new int[6];

                                    arreglo[0] = Integer.parseInt(txtNumero1.getText());
                                    arreglo[1] = Integer.parseInt(txtNumero2.getText());
                                    arreglo[2] = Integer.parseInt(txtNumero3.getText());
                                    arreglo[3] = Integer.parseInt(txtNumero4.getText());
                                    arreglo[4] = Integer.parseInt(txtNumero5.getText());
                                    arreglo[5] = Integer.parseInt(txtNumero6.getText());

                                    String op;

                                    op = cbxOrdenamiento.getSelectedItem().toString();

                                    if (op == "Burbuja") {

                                        int n1 = Integer.parseInt(txtContador.getText());
                                        int n2 = Integer.parseInt(txtContador2.getText());
                                        int n3 = 1;

                                        for (int i = 0; i < n3; i++) {

                                            for (int j = n1; j < n2; j++) {

                                                if (arreglo[j] > arreglo[j + 1]) {
                                                    int aux = arreglo[j];
                                                    arreglo[j] = arreglo[j + 1];
                                                    arreglo[j + 1] = aux;

                                                    n1 += 1;
                                                    j = 5;
                                                    n3 = 1;

                                                } else {

                                                    n1 += 1;
                                                    j = 5;
                                                    n3++;

                                                }

                                                if (n1 == n2) {
                                                    n1 = 0;
                                                    n2 = n2 - 1;
                                                }

                                            }

                                            txtNumero1.setText(Integer.toString(arreglo[0]));
                                            txtNumero2.setText(Integer.toString(arreglo[1]));
                                            txtNumero3.setText(Integer.toString(arreglo[2]));
                                            txtNumero4.setText(Integer.toString(arreglo[3]));
                                            txtNumero5.setText(Integer.toString(arreglo[4]));
                                            txtNumero6.setText(Integer.toString(arreglo[5]));
                                            txtContador.setText(Integer.toString(n1));
                                            txtContador2.setText(Integer.toString(n2));
                                        }
                                    }

                                    if (op == "Seleccion") {

                                        int n4 = Integer.parseInt(txtContador.getText());
                                        int n5 = n4 + 1;

                                        if (n4 < 5) {

                                            for (int i = n4; i < n5; i++) {
                                                for (int j = i; j < arreglo.length; j++) {
                                                    if (arreglo[i] > arreglo[j]) {
                                                        Integer aux = arreglo[j];
                                                        arreglo[j] = arreglo[i];
                                                        arreglo[i] = aux;

                                                    }
                                                }
                                                n4++;

                                                txtNumero1.setText(Integer.toString(arreglo[0]));
                                                txtNumero2.setText(Integer.toString(arreglo[1]));
                                                txtNumero3.setText(Integer.toString(arreglo[2]));
                                                txtNumero4.setText(Integer.toString(arreglo[3]));
                                                txtNumero5.setText(Integer.toString(arreglo[4]));
                                                txtNumero6.setText(Integer.toString(arreglo[5]));

                                            }

                                            txtContador.setText(Integer.toString(n4));
                                        }
                                    }

                                    if (op == "Insercion") {

                                        int n1 = Integer.parseInt(txtContador.getText());

                                        int n2 = n1 + 1;

                                        for (int i = n1; i < n2; i++) {
                                            int aux = arreglo[i];
                                            int j = i;

                                            while (j > 0 && arreglo[j - 1] > aux) {
                                                arreglo[j] = arreglo[j - 1];
                                                j--;
                                            }
                                            arreglo[j] = aux;
                                            n1++;
                                        }

                                        txtNumero1.setText(Integer.toString(arreglo[0]));
                                        txtNumero2.setText(Integer.toString(arreglo[1]));
                                        txtNumero3.setText(Integer.toString(arreglo[2]));
                                        txtNumero4.setText(Integer.toString(arreglo[3]));
                                        txtNumero5.setText(Integer.toString(arreglo[4]));
                                        txtNumero6.setText(Integer.toString(arreglo[5]));
                                        txtContador.setText(Integer.toString(n1));
                                    }
                                } catch (Exception e) {

                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1MouseClicked

    private void txtNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero1ActionPerformed

    private void txtContador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContador2ActionPerformed

    private void txtContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContadorActionPerformed

    private void txtNumero5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumero5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        cbxOrdenamiento.setEnabled(true);

        txtNumero1.setText("");
        txtNumero2.setText("");
        txtNumero3.setText("");
        txtNumero4.setText("");
        txtNumero5.setText("");
        txtNumero6.setText("");
        
        txtContador.setText("0");
        txtContador2.setText("5");

        txtNumero1.setEnabled(true);
        txtNumero2.setEnabled(true);
        txtNumero3.setEnabled(true);
        txtNumero4.setEnabled(true);
        txtNumero5.setEnabled(true);
        txtNumero6.setEnabled(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxOrdenamiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtContador;
    private javax.swing.JTextField txtContador2;
    public javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtNumero2;
    private javax.swing.JTextField txtNumero3;
    private javax.swing.JTextField txtNumero4;
    private javax.swing.JTextField txtNumero5;
    private javax.swing.JTextField txtNumero6;
    // End of variables declaration//GEN-END:variables
}
